SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES * B.PRICE) TOTAL_SALES
FROM BOOK_SALES S LEFT JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID LEFT JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE SUBSTR(S.SALES_DATE, 1, 7) = '2022-01'
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY 1, 3 DESC