
# SELECT MILK.CART_ID
# FROM (SELECT CART_ID
#     FROM CART_PRODUCTS
#     WHERE NAME = 'Milk')  MILK INNER JOIN (SELECT CART_ID
#                                       FROM CART_PRODUCTS
#                                       WHERE NAME = 'Yogurt') YOGURT ON MILK.CART_ID = YOGURT.CART_ID


SELECT CART_ID
FROM CART_PRODUCTS
GROUP BY CART_ID
HAVING GROUP_CONCAT(NAME) LIKE '%Milk%' AND GROUP_CONCAT(NAME) LIKE '%Yogurt%'
ORDER BY 1