# SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') SALES_DATE,
#         PRODUCT_ID, USER_ID, SALES_AMOUNT
# FROM ONLINE_SALE
# WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3
# ORDER BY 1, 2, 3
# UNION
# SELECT DATE_FORMAT(DATE(SALES_DATE), '%Y-%m-%d') SALES_DATE,
#         PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
# FROM OFFLINE_SALE
# WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3
# ORDER BY 1, 2, 3


SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'
UNION
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID