# WITH CTE AS(
# SELECT C.CAR_ID, C.CAR_TYPE, 
#         CASE WHEN C.CAR_TYPE = '세단' THEN C.DAILY_FEE * 0.9 * 30
#              WHEN C.CAR_TYPE = 'SUV' THEN C.DAILY_FEE * 0.92 * 30 END FEE
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H LEFT JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
# WHERE C.CAR_TYPE IN ('SUV', '세단')
#     AND (H.START_DATE > '2022-11-30' OR H.END_DATE < '2022-11-01')
#    ) 
# SELECT CAR_ID, CAR_TYPE, ROUND(FEE, 0) FEE
# FROM CTE
# WHERE FEE >= 500000 AND FEE < 2000000
# GROUP BY 1
# ORDER BY 3 DESC, 2, 1 DESC






# SELECT DISTINCT(C.CAR_ID), C.CAR_TYPE
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H LEFT JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID 
# WHERE C.CAR_TYPE IN ('SUV', '세단')
#       AND (H.START_DATE > '2022-11-30' OR H.END_DATE < '2022-11-01')


-- 해당 기간에 대여 기록이 있는 차 리스트 뽑기
# SELECT DISTINCT H.CAR_ID
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H LEFT JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID 
# WHERE H.START_DATE <= '2022-11-30' AND H.END_DATE >= '2022-11-01'

-- --- 

WITH CTE AS(
SELECT C.CAR_ID, C.CAR_TYPE, 
        CASE WHEN C.CAR_TYPE = '세단' THEN C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE/100)
             WHEN C.CAR_TYPE = 'SUV' THEN C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE/100) END FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H LEFT JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
        LEFT JOIN (SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '30일 이상') P ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('SUV', '세단')
    AND C.CAR_ID NOT IN (SELECT DISTINCT H.CAR_ID
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H LEFT JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID 
                        WHERE H.START_DATE < '2022-11-30' AND H.END_DATE > '2022-11-01')
   ) 
SELECT DISTINCT(CAR_ID), CAR_TYPE, ROUND(FEE, 0) FEE
FROM CTE
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY 3 DESC, 2, 1 DESC



# SELECT *
# FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
# WHERE DURATION_TYPE = '30일 이상'

# SELECT *
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H LEFT JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
#         LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
# LIMIT 5