SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
    SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES,
        RANK() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) FAV_RANK
    FROM REST_INFO
    ORDER BY FOOD_TYPE DESC ) a
WHERE a.FAV_RANK = 1