-- 코드를 입력하세요
SELECT R.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE), 2) SCORE
FROM REST_REVIEW R LEFT JOIN REST_INFO I ON R.REST_ID = I.REST_ID
WHERE SUBSTR(I.ADDRESS, 1, 2) = '서울'
GROUP BY 1
ORDER BY SCORE DESC, 4 DESC