-- 코드를 입력하세요
SELECT SUBSTR(S.SALES_DATE, 1, 4) YEAR, DATE_FORMAT(S.SALES_DATE, '%m') MONTH, U.GENDER, COUNT(DISTINCT S.USER_ID) USERS
FROM ONLINE_SALE S LEFT JOIN USER_INFO U ON S.USER_ID = U.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3