
# SELECT YEAR(S.SALES_DATE) YEAR, MONTH(S.SALES_DATE) MONTH, 
#         COUNT(DISTINCT S.USER_ID) PURCHASED_USERS
#         ROUND(COUNT(DISTINCT S.USER_ID) / COUNT(), 1) PURCHASED_RATIO

# FROM ONLINE_SALE S LEFT JOIN USER_INFO U ON U.USER_ID = S.USER_ID
# WHERE U.JOINED BETWEEN '2021-01-01' AND '2021-12-31'
# GROUP BY 1, 2
# ORDER BY 1, 2





# SELECT YEAR(S.SALES_DATE) YEAR,
#        MONTH(S.SALES_DATE) MONTH,
#        COUNT(DISTINCT S.USER_ID) PURCHASED_USERS,
#        ROUND(COUNT(DISTINCT S.USER_ID) / COUNT(DISTINCT SUB.USER_ID), 1) PURCHASED_RATIO
# SELECT *
# FROM (

#     SELECT YEAR(S.SALES_DATE) YEAR,
#        MONTH(S.SALES_DATE) MONTH,
#        # COUNT(DISTINCT S.USER_ID) PURCHASED_USERS,
#        # COUNT(DISTINCT U.USER_ID) EVERY_USERS,
#     ROUND(COUNT(DISTINCT S.USER_ID) / COUNT(DISTINCT U.USER_ID), 1) PURCHASED_RATIO
#       FROM USER_INFO U LEFT JOIN ONLINE_SALE S ON U.USER_ID = S.USER_ID
#       WHERE U.JOINED BETWEEN '2021-01-01' AND '2021-12-31'
# -- )SUB
# GROUP BY 1, 2
# ORDER BY 1, 2




# SELECT *
# FROM ONLINE_SALE
# WHERE USER_ID IN (SELECT USER_ID
#                     FROM USER_INFO U
#                     WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31')
                    
WITH CTE AS (SELECT COUNT(USER_ID) ALL_COUNT
FROM USER_INFO
WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31')
SELECT YEAR(SALES_DATE) YEAR,
       MONTH(SALES_DATE) MONTH,
       COUNT(DISTINCT USER_ID) PURCHASED_USERS,
       ROUND(COUNT(DISTINCT USER_ID) / (SELECT ALL_COUNT FROM CTE), 1) PURCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (SELECT USER_ID
                    FROM USER_INFO U
                    WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31')
GROUP BY 1, 2
ORDER BY 1, 2
