# SELECT ID,  NAME, S.HOST_ID
# FROM (SELECT HOST_ID
#     FROM PLACES
#     GROUP BY HOST_ID
#     HAVING COUNT(ID) > 1
#     ORDER BY ID) S LEFT JOIN PLACES P ON S.HOST_ID = P.HOST_ID
# ORDER BY ID

SELECT ID, NAME, HOST_ID
FROM PLACES
WHERE HOST_ID IN (SELECT HOST_ID
                 FROM PLACES
                  GROUP BY HOST_ID
                 HAVING COUNT(ID) >=  2)
ORDER BY ID