
# SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(P.PRICE * O.AMOUNT) TOTAL_SALES
# FROM FOOD_ORDER O LEFT JOIN FOOD_PRODUCT P ON O.PRODUCT_ID = P.PRODUCT_ID
# WHERE SUBSTR(O.PRODUCE_DATE, 1, 7) = '2022-05'
# ORDER BY TOTAL_SALES, 1

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(P.PRICE * O.AMOUNT) TOTAL_SALES
FROM FOOD_ORDER O LEFT JOIN FOOD_PRODUCT P ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE SUBSTR(O.PRODUCE_DATE, 1, 7) = '2022-05'
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, 1