WITH TRUCKS AS (SELECT H.HISTORY_ID, H.CAR_ID, C.CAR_TYPE, C.DAILY_FEE, 
                    DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS DAYS,
                    CASE WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
                         WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
                         WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
                         ELSE '-' END DURA
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H LEFT JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭')
SELECT T.HISTORY_ID, -- T.CAR_ID, T.DAILY_FEE, T.DAYS, T.DURA, P.DISCOUNT_RATE,
        ROUND(T.DAYS * T.DAILY_FEE * (1-COALESCE(DISCOUNT_RATE, 0)/100), 0) FEE
FROM TRUCKS T LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON T.CAR_TYPE = P.CAR_TYPE AND T.DURA = P.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC




# SELECT *
# FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
# WHERE CAR_TYPE = '트럭'