-- 코드를 입력하세요
# SELECT J.FLAVOR
# FROM JULY J LEFT JOIN FIRST_HALF F ON J.SHIPMENT_ID = F.SHIPMENT_ID
# GROUP BY J.FLAVOR
# ORDER BY (SUM(J.TOTAL_ORDER) + SUM(F.TOTAL_ORDER)) DESC
# LIMIT 3

# SELECT *, (F.TOTAL_ORDER + J.TOTAL_ORDER) ALL_TOTAL
# FROM JULY J LEFT JOIN FIRST_HALF F ON J.SHIPMENT_ID = F.SHIPMENT_ID

# SELECT S.FLAVOR
# FROM (SELECT *, SUM(TOTAL_ORDER)
#     FROM JULY
#     GROUP BY FLAVOR) S LEFT JOIN FIRST_HALF F ON S.SHIPMENT_ID = F.SHIPMENT_ID
# ORDER BY (S.TOTAL_ORDER + F.TOTAL_ORDER) DESC
# LIMIT 3

SELECT S.FLAVOR
FROM (SELECT *, SUM(TOTAL_ORDER) TOTAL2
    FROM JULY
    GROUP BY FLAVOR) S LEFT JOIN FIRST_HALF F ON S.SHIPMENT_ID = F.SHIPMENT_ID
GROUP BY S.FLAVOR
ORDER BY (S.TOTAL2 + F.TOTAL_ORDER) DESC
LIMIT 3