SELECT T2.ITEM_ID, I2.ITEM_NAME, I2.RARITY
FROM ((ITEM_INFO I1 JOIN ITEM_TREE T ON T.PARENT_ITEM_ID = I1.ITEM_ID)
    JOIN ITEM_TREE T2 ON T.ITEM_ID = T2.ITEM_ID) 
    JOIN ITEM_INFO I2 ON T2.ITEM_ID = I2.ITEM_ID
WHERE I1.RARITY = 'RARE'
ORDER BY 1 DESC