-- 코드를 입력하세요
SELECT MCDP_CD '진료과 코드', COUNT(APNT_NO) '5월예약건수'
FROM APPOINTMENT
WHERE DATE_FORMAT(DATE(APNT_YMD), '%m') = 5
GROUP BY 1
ORDER BY 2, 1

# SELECT DATE_FORMAT(DATE(APNT_YMD), '%m')
# FROM APPOINTMENT