SELECT MONTH(START_DATE) MONTH, CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT  CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
    ORDER BY CAR_ID DESC) AND (START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31')
GROUP BY MONTH, CAR_ID
HAVING RECORDS > 0
ORDER BY 1, 2 DESC
