-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(S.SALES) TOTAL_SLAES
FROM BOOK_SALES S LEFT JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
WHERE DATE_FORMAT(S.SALES_DATE, '%Y') = 2022 AND DATE_FORMAT(S.SALES_DATE, '%m') = 01
GROUP BY 1
ORDER BY 1