SELECT CATEGORY, PRICE NAX_PRICE, PRODUCT_NAME
FROM (
SELECT CATEGORY, PRODUCT_NAME, PRICE,
    RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) PRICE_RANK
FROM FOOD_PRODUCT
    ) a
WHERE PRICE_RANK = 1 AND CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY PRICE DESC
